name: Deploy Friends Services to EC2

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for add and get friends services
      run: |
        docker build -t kamartinez/add_friend ./add_friend
        docker build -t kamartinez/get_friend ./get_friend

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kamartinez/add_friend
        docker push kamartinez/get_friend

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 44.193.181.80 
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Detener y eliminar contenedores anteriores si existen
          docker stop add_friend || true
          docker rm add_friend || true
          docker stop get_friend || true
          docker rm get_friend || true

          # Descargar las últimas imágenes de Docker
          docker pull kamartinez/add_friend
          docker pull kamartinez/get_friend

          # Ejecutar los nuevos contenedores con las imágenes más recientes
          docker run -d --name add_friend -p 8000:8000 kamartinez/add_friend
          docker run -d --name get_friend -p 8001:8001 kamartinez/get_friend
