name: Deploy friends-service-python to EC2

on:
  push:
    branches:
      - test  # Cambia si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 54.236.126.209
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "📦 Pulling latest Docker image..."
          docker pull kamartinez/friends-service-python:latest
          
          echo "🧹 Cleaning up port 8083 if in use..."
          docker ps -q --filter "publish=8083" | grep . && docker stop $(docker ps -q --filter "publish=8083") && docker rm $(docker ps -aq --filter "publish=8083") || echo "✅ Port 8083 is free"

          echo "🚀 Starting new container..."
          docker run -d --name friends-service-python --restart unless-stopped -p 8083:8000 kamartinez/friends-service-python:latest

          echo "✅ Deployment completed!"
