name: Deploy friends-service-python to EC2

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 44.193.181.80
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "📦 Pulling latest Docker image..."
          docker pull kamartinez/friends-service-python:latest

          echo "🚀 Starting new container (or replacing existing one)..."
          docker stop friends-service-python || true
          docker rm friends-service-python || true

          docker run -d \
            --name friends-service-python \
            --restart unless-stopped \
            -p 8083:8000 \
            kamartinez/friends-service-python:latest

          echo "✅ Deployment completed!"
